services:
  ani-gamer-next:
    build:
      context: .
    image: anigamerplus
    container_name: "ani-gamer-next"
    volumes:
      - "./downloads:/app/bangumi"
      - type: bind
        source: ./config.json
        target: /app/config.json
      - type: bind
        source: ./aniGamer.db
        target: /app/aniGamer.db
    ports:
      - "5000:5000"
    restart: unless-stopped
