#anigamerplus latest python build

name: aniGamerPlus Build Artifact

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python: [3.8.x, 3.9.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with: 
          python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build exe
      run: pyinstaller --noconfirm --distpath %cd%\ --onefile --console --icon %cd%\Dashboard\static\img\favicon.ico --clean --add-data %cd%;aniGamerPlus/  %cd%\aniGamerPlus.py
      shell: cmd
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
       name: aniGamerPlus_artifacts_${{ matrix.python }}
       path: |
         aniGamerPlus.exe
         Dashboard/
         LICENSE
         README.md
         DanmuTemplate.ass
         sn_list-sample.txt
         config-sample.json
